# Generated by Django 5.2.15 on 2026-06-25 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_jti', models.CharField(db_index=True, max_length=350)),
                ('refresh_token_jti', models.CharField(db_index=True, max_length=250)),
                ('device_name', models.CharField(default='unknown_device', max_length=255)),
                ('browser_name', models.CharField(default='Uknown_browser', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_4f7411_idx')],
            },
        ),
    ]
