# Generated by Django 6.0.6 on 2026-06-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('saving', 'Saving'), ('current', 'Current'), ('student', 'Student')], max_length=50),
        ),
    ]
