# Generated by Django 6.0.6 on 2026-06-18 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nid', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='bank_user_email_a5bfc0_idx'), models.Index(fields=['phone'], name='bank_user_phone_076397_idx'), models.Index(fields=['created_at'], name='bank_user_created_283a2c_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_user_email'), models.UniqueConstraint(fields=('phone',), name='unique_user_phone'), models.UniqueConstraint(fields=('nid',), name='unique_user_nid')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('Savings', 'savings'), ('Current', 'current'), ('Business', 'business')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='allserializer.user')),
            ],
            options={
                'db_table': 'bank_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'deposit'), ('Withdraw', 'withdraw'), ('Transfer', 'transfer')], max_length=20)),
                ('transaction_status', models.CharField(choices=[('Pending', 'pending'), ('Successful', 'successful'), ('Failed', 'failed')], default='Pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='allserializer.account')),
            ],
            options={
                'db_table': 'bank_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account'], name='bank_transa_account_3b9095_idx'), models.Index(fields=['transaction_type'], name='bank_transa_transac_5279ed_idx'), models.Index(fields=['transaction_status'], name='bank_transa_transac_a68340_idx'), models.Index(fields=['created_at'], name='bank_transa_created_d1647d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'), models.UniqueConstraint(fields=('account', 'created_at'), name='unique_account_transaction')],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='bank_accoun_account_1885ed_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='bank_accoun_user_id_c7a79c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='bank_accoun_is_acti_fb51b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='account_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('account_number',), name='unique_account_number'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'account_number'), name='unique_user_account'),
        ),
    ]
